on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Lint

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin
      - run: npm install
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: "."
          key: api-${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: api-${{ github.sha }}
      - run: npm run lint
